### ISSUE TITLE
Club's logo 

### ISSUE THREAD

**Issue by markroxor** [RoboISM/Roboism#10]
Club's logo on the title bar next to "RoboISM".

![s](https://avatars3.githubusercontent.com/u/24591384?v=3&s=200)
This is our clubs logo.
*Is it currently used by some organisation? or was it built from scratch* Find out.
If original, make it official everywhere including the fb club page profile picture.

**Comment by devojoyti** [comment]
Yes, it is our official logo. It was designed by our second year, built from scratch.
