### ISSUE TITLE
Linked in button throws a django error

### ISSUE THREAD

**Issue by markroxor** [RoboISM/Roboism#6]
![image](https://cloud.githubusercontent.com/assets/11366315/21470191/99f373da-caa3-11e6-833d-80e931e3a123.png)

The linkedin button throws this default Django error
![image](https://cloud.githubusercontent.com/assets/11366315/21470194/c24c2444-caa3-11e6-95ff-605fc58fbbb4.png)

Either fix the cause of error or find a better way of throwing this error.

**Comment by devojoyti** [comment]
Bug fixed in commit [a74f343f515be992ffb9664d303bb9e163d611aa](https://github.com/RoboISM/Roboism/commit/a74f343f515be992ffb9664d303bb9e163d611aal)
