### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by markroxor** [RoboISM/Roboism#7]
Currently this is the 404 error.
http://roboism.pythonanywhere.com/bnb

Change it to something like this - 
http://markroxor.github.io/hghjh

**Comment by devojoyti** [comment]
Fixed in commit [a74f343f515be992ffb9664d303bb9e163d611aa](https://github.com/RoboISM/Roboism/commit/a74f343f515be992ffb9664d303bb9e163d611aa)
